from __future__ import annotations

from socialapi._client import AsyncSocialAPI, SocialAPI
from socialapi._constants import (
    ConversationStatus,
    ErrorCategory,
    ErrorCausedBy,
    MessageDirection,
    ModerationAction,
    Platform,
    PostStatus,
    TargetStatus,
    Visibility,
    WebhookEvent,
)
from socialapi._exceptions import (
    AccountAlreadyLinkedError,
    AccountNotFoundError,
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    InternalServerError,
    InvalidCredentialsError,
    InvalidTokenError,
    MissingMetadataError,
    NotFoundError,
    NotSupportedError,
    PlatformRateLimitError,
    RateLimitError,
    SocialAPIError,
    StorageQuotaExceededError,
    UnsupportedPlatformError,
)
from socialapi._pagination import AsyncCursorPage, CursorPage
from socialapi._version import __version__
from socialapi.models import (
    Account,
    AccountLimits,
    APIKey,
    Brand,
    CommentCapabilities,
    CommentedPost,
    ConnectAccountRequest,
    ConnectAccountResponse,
    ConnectOAuthResponse,
    Conversation,
    CreateBrandRequest,
    CreateInviteRequest,
    CreateKeyRequest,
    CreateKeyResponse,
    CreatePostRequest,
    CreateWebhookRequest,
    CreateWebhookResponse,
    Event,
    EventsListResponse,
    ImportPostsResponse,
    ImportRowError,
    InboxComment,
    Invite,
    InviteListItem,
    MediaItem,
    MediaUploadResponse,
    MediaUploadURL,
    Mention,
    Message,
    OAuthExchangeRequest,
    OAuthExchangeResponse,
    PlatformConstraints,
    Post,
    PostMetrics,
    PostTarget,
    PostTargetError,
    PostTargetMetrics,
    PrivateReplyRequest,
    ReplyToCommentRequest,
    ReplyToCommentResponse,
    ReplyToReviewRequest,
    ReplyToReviewResponse,
    Review,
    SendFeedbackRequest,
    SendMessageRequest,
    SendMessageResponse,
    StorageUsage,
    TargetRequest,
    UnpublishRequest,
    UpdateBrandRequest,
    UpdateConversationRequest,
    UpdatePostRequest,
    UpdateReviewReplyRequest,
    UpdateUserRequest,
    UpdateWebhookRequest,
    UsageResponse,
    User,
    ValidatePostRequest,
    ValidationIssue,
    ValidationResult,
    Webhook,
)

__all__: list[str] = [  # noqa: RUF022
    # Client classes
    "SocialAPI",
    "AsyncSocialAPI",
    # Version
    "__version__",
    # Pagination
    "CursorPage",
    "AsyncCursorPage",
    # Constants / enums
    "Platform",
    "PostStatus",
    "TargetStatus",
    "Visibility",
    "ModerationAction",
    "ConversationStatus",
    "MessageDirection",
    "WebhookEvent",
    "ErrorCategory",
    "ErrorCausedBy",
    # Exceptions
    "SocialAPIError",
    "APIStatusError",
    "APIConnectionError",
    "APITimeoutError",
    "BadRequestError",
    "UnsupportedPlatformError",
    "MissingMetadataError",
    "AuthenticationError",
    "InvalidTokenError",
    "InvalidCredentialsError",
    "ForbiddenError",
    "NotFoundError",
    "AccountNotFoundError",
    "ConflictError",
    "AccountAlreadyLinkedError",
    "StorageQuotaExceededError",
    "RateLimitError",
    "PlatformRateLimitError",
    "InternalServerError",
    "NotSupportedError",
    # Models -- accounts
    "Account",
    "ConnectAccountRequest",
    "ConnectAccountResponse",
    "ConnectOAuthResponse",
    "OAuthExchangeRequest",
    "OAuthExchangeResponse",
    # Models -- brands
    "Brand",
    "CreateBrandRequest",
    "UpdateBrandRequest",
    # Models -- comments
    "CommentCapabilities",
    "CommentedPost",
    "InboxComment",
    "PrivateReplyRequest",
    "ReplyToCommentRequest",
    "ReplyToCommentResponse",
    # Models -- conversations
    "Conversation",
    "Message",
    "SendMessageRequest",
    "SendMessageResponse",
    "UpdateConversationRequest",
    # Models -- events
    "Event",
    "EventsListResponse",
    # Models -- feedback
    "SendFeedbackRequest",
    # Models -- invites
    "Invite",
    "InviteListItem",
    "CreateInviteRequest",
    # Models -- keys
    "APIKey",
    "CreateKeyRequest",
    "CreateKeyResponse",
    # Models -- media
    "MediaItem",
    "StorageUsage",
    # Models -- mentions
    "Mention",
    # Models -- posts
    "Post",
    "PostMetrics",
    "PostTarget",
    "PostTargetError",
    "PostTargetMetrics",
    "ValidationIssue",
    "ValidationResult",
    # Models -- publishing
    "CreatePostRequest",
    "ImportPostsResponse",
    "ImportRowError",
    "MediaUploadResponse",
    "MediaUploadURL",
    "PlatformConstraints",
    "TargetRequest",
    "UnpublishRequest",
    "UpdatePostRequest",
    "ValidatePostRequest",
    # Models -- reviews
    "ReplyToReviewRequest",
    "ReplyToReviewResponse",
    "Review",
    "UpdateReviewReplyRequest",
    # Models -- usage
    "AccountLimits",
    "UsageResponse",
    # Models -- users
    "UpdateUserRequest",
    "User",
    # Models -- webhooks
    "CreateWebhookRequest",
    "CreateWebhookResponse",
    "UpdateWebhookRequest",
    "Webhook",
]
